service: eng-metrics-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment: ${file(.env.yml):}

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
  stage: "${opt:stage, self:provider.stage}"
  region: "us-east-1"

functions:
  backlogs:
    handler: functions/backlog-handlers.backlogs
    events:
      - http:
         path: /backlogs
         method: get
         cors: true
  backlog-epics:
    handler: functions/backlog-handlers.backlogEpics
    timeout: 20
    events:
      - http:
          path: /backlogs/{backlogId}/epics
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 3600
            cacheKeyParameters:
              - name: request.path.backlogId
  epic-issues:
    handler: functions/backlog-handlers.epicIssues
    events:
        - http:
            path: /backlogs/{backlogId}/epics/{epicId}/epicIssues
            method: get
            cors: true
  export-backlog-epic-google-sheet:
      handler: functions/google-doc-handlers.exportBacklogEpicsToGoogleSheet
      timeout: 20