service: eng-metrics-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  backlogs:
    handler: functions/backlog-handlers.backlogs
    events:
      - http:
         path: /backlogs
         method: get
