service: eng-metrics-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment: ${file(.env.yml):}

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
  stage: "${opt:stage, self:provider.stage}"
  region: "us-east-1"

functions:
  backlog-epics:
    handler: functions/backlog-handlers.backlogEpics
    timeout: 20
    events:
      - http:
          path: /backlogs/{backlogId}/epics
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 3600
            cacheKeyParameters:
              - name: request.path.backlogId